language: node_js
node_js:
  - "5"

# Use faster Docker architecture on Travis.
sudo: false

script:
  - npm test
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy
